# Generated by Django 4.2.1 on 2023-05-13 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('language', models.CharField(max_length=20)),
                ('grade', models.IntegerField(default=None, null=True)),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='diary.course')),
            ],
        ),
    ]
