name: Run Linter and Tests
on:
  - push
  - pull_request

jobs:
  execute_linter_and_tests:
    name: Install requirements and execute linter&tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install requirements
        run: pip install -r lesson_11/school/requirements.txt
      - name: Execute flake8 linter
        run: flake8 lesson_11/school --config lesson_11/school/.flake8
      - name: Execute tests
        run: pytest lesson_11/school/
