name: Run Linter and Tests
on:
  - push
  - pull_request

jobs:
  execute_linter_and_tests:
    name: Install requirements and execute linter&tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install requirements
        run: pip install flake8
      - name: Execute flake8 linter
        run: flake8 PyLessons/lesson_11/school --config PyLessons/lesson_11/school/flake8
      - name: Execute tests
        run: pytest PyLessons/lesson_11/school/flake8
